### ISSUE TITLE
Alternative part for TLV70019

### ISSUE THREAD

**Issue by JeremyBois** [Ariamelon/Ogen#4]
Hi,

I want to use [**JLCPCB**](https://jlcpcb.com/) service to print and assemble your board (thanks by the way !). 

However the part `TLV70019` is out of stock ([TLV70019](https://jlcpcb.com/partdetail/TexasInstruments-TLV70019DDCR/C2862411)) and I am looking for an alternative. 
I found one which seems equivalent and in stock ([VRH1902LTX](https://jlcpcb.com/partdetail/Anasem-VRH1902LTX/C697975)).

Can you tell me if [VRH1902LTX](https://jlcpcb.com/partdetail/Anasem-VRH1902LTX/C697975) can be used in place of [TLV70019](https://jlcpcb.com/partdetail/TexasInstruments-TLV70019DDCR/C2862411) ?

Have a nice day,

**Comment by JeremyBois** [comment]
I made a [fork](https://github.com/JeremyBois/Ogen) with:
  - [VRH1902LTX](https://jlcpcb.com/partdetail/Anasem-VRH1902LTX/C697975) in place of [TLV70019](https://jlcpcb.com/partdetail/TexasInstruments-TLV70019DDCR/C2862411)
  - BOM and POS files as required for JLCPCB assembling service
  - Embed datasheet for VRH1902LTX and PMW3360DM-T2QU parts


The PCB is in production right now. I will update / close this issue once I can confirm that the modification does work.

**Comment by BenRoe** [comment]
@JeremyBois does it work with the VRH1902LTX ?

**Comment by JeremyBois** [comment]
> @JeremyBois does it work with the VRH1902LTX ?

Not yet tested. 
I receive the PCBs and I am working on the QMK configuration for my keyboard right now.
When the trackball will be fully working I will close this issue.

**Comment by JeremyBois** [comment]
I can confirm that the sensor does work with VRH1902LTX part as a replacement. 
Tested on my [keyboard with QMK](https://github.com/JeremyBois/qmk-ptechinos/tree/KB2040).

Feel free to use my [fork](https://github.com/JeremyBois/Ogen) for manufacturing.

**Comment by buitrung** [comment]
Hi @JeremyBois, I find your repo really useful.
However I'm new to these pcb things, so please help me with my dumb question.

Is it that I can upload your [gerber file](https://github.com/JeremyBois/Ogen/blob/main/PCB/data/production/V1.2/OgenV1.2-Gerbers.zip) to JLC and check the option "PCB assembly" and that's all?
Does your board will come with every little part on it?
Does it come with the main sensor or do I have to get it separately then solder on the board?

Thanks for your help.

**Comment by buitrung** [comment]
I've just play around with JLC and seem to have figured this out...
I upload your v1.2 gerber file, then upload the bom.csv & positions.csv for BOM & CPL in the BOM screen and get the final result in a 2d/3d renderer, in which the main sensor is missing (I may possibly solder it by myself).

Thanks for your fantastic work!

**Comment by JeremyBois** [comment]
> Does your board will come with every little part on it?

All but the sensor and its lens.

> Is it that I can upload your [gerber file](https://github.com/JeremyBois/Ogen/blob/main/PCB/data/production/V1.2/OgenV1.2-Gerbers.zip) to JLC and check the option "PCB assembly" and that's all?

You need to upload:
  - gerber files 
  - bom.csv
  - positions.csv

> Does it come with the main sensor or do I have to get it separately then solder on the board?

No the sensor and lens have to be bought separately (JLC manufacturing service is only for SMD parts).

> I upload your v1.2 gerber file, then upload the bom.csv & positions.csv for BOM & CPL in the BOM screen and get the final result in a 2d/3d renderer, in which the main sensor is missing (I may possibly solder it by myself).

Yes you understand it correctly. Please double check that each component is in the right position / orientation before processing further (just in case). On each part there is a little circle (see github PCB images) which show where the first pin should be. If I remember correctly there JLC use a red circle to show where the first pin will be.

If you are unsure feel free to ask.

**Comment by buitrung** [comment]
Good to know to confirm the correct orientation of parts. I did not do that but the result was still correct. I have placed the order and will confirm if it works (or even not).
