### ISSUE TITLE
PCB working but not with longer jumper cables

### ISSUE THREAD

**Issue by rftw** [Ariamelon/Ogen#7]
I got V1.2 pcbs from jlcpcb. Bought sensor lens from [aliexpress ](https://www.aliexpress.us/item/2255800717950849.html). Soldered it on the pcb and connected it to blue promicro using 7.5cm (3") F-F jumper cables. Working great. 

However when using jumper wires greater than 10cm, it's not working. The sensor is getting the power. I can see the red light from an angle, but there is no movement. I also have [MrJohnK pcb from tindie](https://www.tindie.com/products/jkicklighter/pmw3360-motion-sensor/). With MrJohnK pcb, and nothing else changed in the setup (jumper wires, blue promicro), the sensor started working even with jumper cables >30cm. Your pcb is working only with <10cm wire. 

What could explain this behavior?

**Comment by ghostlybutterfly** [comment]
Hi I'm really sorry but I have no idea what could cause this! Have you soldered the MISO pullup jumper? Maybe that could be the cause for it not working.

**Comment by rftw** [comment]
I soldered the jumper but it seems to have no effect. The breakout is working great with sockets or with smaller length jumper cables. Must have been gone something wrong with the jlcpcb assembly. 
I noticed you've made some design modifications. I'll soon give it a try. 
Thank you for this amazing repo!
